name: Send Email with Postmark

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        env:
          POSTMARK_API_KEY: ${{ secrets.POSTMARK_API_KEY }}
        run: |
          curl -X POST https://api.postmarkapp.com/email \
          -H "X-Postmark-Server-Token: $POSTMARK_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "From": "your-email@example.com",
            "To": "recipient@example.com",
            "Subject": "GitHub Event Notification",
            "TextBody": "A GitHub event has occurred. Details: ${GITHUB_EVENT_NAME} on ${GITHUB_REPOSITORY}."
          }'
