name: Send Email on Event

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        env:
          EMAIL_API_URL: ${{ secrets.SENDGRID_API_URL }}
          EMAIL_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          curl -X POST $EMAIL_API_URL \
          -H "Authorization: Bearer $EMAIL_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "personalizations": [
              {
                "to": [
                  {"email": "recipient@example.com"}
                ],
                "subject": "GitHub Event Notification"
              }
            ],
            "from": {"email": "your-email@example.com"},
            "content": [
              {
                "type": "text/plain",
                "value": "A GitHub event has occurred. Details: ${GITHUB_EVENT_NAME} on ${GITHUB_REPOSITORY}."
              }
            ]
          }'
